package com.xuebingdu.frontend.service;


public class MailTemplate {
	public static final String itemTemplate = "\n" + "              <tr>\n"
	   + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #000000;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\n"
	   + "                    class=\"article\">\n"
	   + "                  <img src=\"{{product-imageUrl}}\" alt=\"{{product-name}}\" width=\"18px\" height=\"18px\" style=\"border-radius: 50%\">\n"
	   + "                  <span> {{product-name}}</span>\n" + "                </td>\n"
	   + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">\n"
	   + "                  <small>{{product-size}}</small></td>\n"
	   + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\n"
	   + "                    align=\"center\">{{product-quantity}}\n" + "                </td>\n"
	   + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #1e2b33;  line-height: 18px;  vertical-align: top; padding:10px 0;\"\n"
	   + "                    align=\"right\">${{product-price}}\n" + "                </td>\n"
	   + "              </tr>\n" + "              <tr>\n"
	   + "                <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\n"
	   + "              </tr>";

	public static final String firstPart = "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n"
	   + "<title> Order confirmation </title>\n" + "<meta name=\"robots\" content=\"noindex,nofollow\"/>\n"
	   + "<meta name=\"viewport\" content=\"width=device-width; initial-scale=1.0;\"/>\n"
	   + "<style type=\"text/css\">\n" + "  @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);\n"
	   + "\n" + "  body {\n" + "    margin: 0;\n" + "    padding: 0;\n" + "    background: #e1e1e1;\n" + "  }\n" + "\n"
	   + "  div, p, a, li, td {\n" + "    -webkit-text-size-adjust: none;\n" + "  }\n" + "\n" + "  .ReadMsgBody {\n"
	   + "    width: 100%;\n" + "    background-color: #ffffff;\n" + "  }\n" + "\n" + "  .ExternalClass {\n"
	   + "    width: 100%;\n" + "    background-color: #ffffff;\n" + "  }\n" + "\n" + "  body {\n"
	   + "    width: 100%;\n" + "    height: 100%;\n" + "    background-color: #e1e1e1;\n" + "    margin: 0;\n"
	   + "    padding: 0;\n" + "    -webkit-font-smoothing: antialiased;\n" + "  }\n" + "\n" + "  html {\n"
	   + "    width: 100%;\n" + "  }\n" + "\n" + "  p {\n" + "    padding: 0 !important;\n"
	   + "    margin-top: 0 !important;\n" + "    margin-right: 0 !important;\n" + "    margin-bottom: 0 !important;\n"
	   + "    margin-left: 0 !important;\n" + "  }\n" + "\n" + "  .visibleMobile {\n" + "    display: none;\n" + "  }\n"
	   + "\n" + "  .hiddenMobile {\n" + "    display: block;\n" + "  }\n" + "\n"
	   + "  @media only screen and (max-width: 600px) {\n" + "    body {\n" + "      width: auto !important;\n"
	   + "    }\n" + "\n" + "    table[class=fullTable] {\n" + "      width: 96% !important;\n" + "      clear: both;\n"
	   + "    }\n" + "\n" + "    table[class=fullPadding] {\n" + "      width: 85% !important;\n"
	   + "      clear: both;\n" + "    }\n" + "\n" + "    table[class=col] {\n" + "      width: 45% !important;\n"
	   + "    }\n" + "\n" + "    .erase {\n" + "      display: none;\n" + "    }\n" + "  }\n" + "\n"
	   + "  @media only screen and (max-width: 420px) {\n" + "    table[class=fullTable] {\n"
	   + "      width: 100% !important;\n" + "      clear: both;\n" + "    }\n" + "\n"
	   + "    table[class=fullPadding] {\n" + "      width: 85% !important;\n" + "      clear: both;\n" + "    }\n"
	   + "\n" + "    table[class=col] {\n" + "      width: 100% !important;\n" + "      clear: both;\n" + "    }\n"
	   + "\n" + "    table[class=col] td {\n" + "      text-align: left !important;\n" + "    }\n" + "\n"
	   + "    .erase {\n" + "      display: none;\n" + "      font-size: 0;\n" + "      max-height: 0;\n"
	   + "      line-height: 0;\n" + "      padding: 0;\n" + "    }\n" + "\n" + "    .visibleMobile {\n"
	   + "      display: block !important;\n" + "    }\n" + "\n" + "    .hiddenMobile {\n"
	   + "      display: none !important;\n" + "    }\n" + "  }\n" + "</style>\n" + "\n" + "\n" + "<!-- Header -->\n"
	   + "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\n"
	   + "  <tr>\n" + "    <td height=\"20\"></td>\n" + "  </tr>\n" + "  <tr>\n" + "    <td>\n"
	   + "      <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\"\n"
	   + "             style=\"border-radius: 10px 10px 0 0;\">\n" + "        <tr class=\"hiddenMobile\">\n"
	   + "          <td height=\"40\"></td>\n" + "        </tr>\n" + "        <tr class=\"visibleMobile\">\n"
	   + "          <td height=\"30\"></td>\n" + "        </tr>\n" + "\n" + "        <tr>\n" + "          <td>\n"
	   + "            <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\n"
	   + "              <tbody>\n" + "              <tr>\n" + "                <td>\n"
	   + "                  <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"left\" class=\"col\">\n"
	   + "                    <tbody>\n" + "                    <tr>\n"
	   + "                      <td align=\"left\"><img\n"
	   + "                          src=\"https://res.cloudinary.com/chaohaodu/image/upload/v1659910561/xuebingdu/_MG_6200_c_rhesw9.jpg\"\n"
	   + "                          width=\"32\" height=\"32\" alt=\"logo\" border=\"0\" style=\"border-radius: 50%\"/></td>\n"
	   + "                    </tr>\n" + "                    <tr class=\"hiddenMobile\">\n"
	   + "                      <td height=\"40\"></td>\n" + "                    </tr>\n"
	   + "                    <tr class=\"visibleMobile\">\n" + "                      <td height=\"20\"></td>\n"
	   + "                    </tr>\n" + "                    <tr>\n"
	   + "                      <td style=\"font-size: 12px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: left;\">\n"
	   + "                        Hello, {{name}}.\n"
	   + "                        <br> Thank you for shopping from our store and for your order.\n"
	   + "                      </td>\n" + "                    </tr>\n" + "                    </tbody>\n"
	   + "                  </table>\n"
	   + "                  <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"right\" class=\"col\">\n"
	   + "                    <tbody>\n" + "                    <tr class=\"visibleMobile\">\n"
	   + "                      <td height=\"20\"></td>\n" + "                    </tr>\n"
	   + "                    <tr>\n" + "                      <td height=\"5\"></td>\n" + "                    </tr>\n"
	   + "                    <tr>\n"
	   + "                      <td style=\"font-size: 21px; color: #000000; letter-spacing: -1px; font-family: 'Open Sans', sans-serif; line-height: 1; vertical-align: top; text-align: right;\">\n"
	   + "                        Invoice\n" + "                      </td>\n" + "                    </tr>\n"
	   + "                    <tr>\n" + "                    <tr class=\"hiddenMobile\">\n"
	   + "                      <td height=\"50\"></td>\n" + "                    </tr>\n"
	   + "                    <tr class=\"visibleMobile\">\n" + "                      <td height=\"20\"></td>\n"
	   + "                    </tr>\n" + "                    <tr>\n"
	   + "                      <td style=\"font-size: 12px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: right;\">\n"
	   + "                        <small>ORDER</small> #{{tracking-number}}<br/>\n"
	   + "                        <small>{{placed-date}}</small>\n" + "                      </td>\n"
	   + "                    </tr>\n" + "                    </tbody>\n" + "                  </table>\n"
	   + "                </td>\n" + "              </tr>\n" + "              </tbody>\n" + "            </table>\n"
	   + "          </td>\n" + "        </tr>\n" + "      </table>\n" + "    </td>\n" + "  </tr>\n" + "</table>\n"
	   + "<!-- /Header -->\n" + "\n" + "\n" + "<!-- Order Details -->\n"
	   + "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\n"
	   + "  <tbody>\n" + "  <tr>\n" + "    <td>\n"
	   + "      <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\">\n"
	   + "        <tbody>\n" + "        <tr>\n" + "        <tr class=\"hiddenMobile\">\n"
	   + "          <td height=\"60\"></td>\n" + "        </tr>\n" + "        <tr class=\"visibleMobile\">\n"
	   + "          <td height=\"40\"></td>\n" + "        </tr>\n" + "        <tr>\n" + "          <td>\n"
	   + "            <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\n"
	   + "              <tbody>\n" + "              <tr>\n"
	   + "                <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 10px 7px 0;\"\n"
	   + "                    width=\"52%\" align=\"left\">\n" + "                  Item\n" + "                </th>\n"
	   + "                <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\"\n"
	   + "                    align=\"left\">\n" + "                  <small>SKU</small>\n" + "                </th>\n"
	   + "                <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\"\n"
	   + "                    align=\"center\">\n" + "                  Quantity\n" + "                </th>\n"
	   + "                <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #1e2b33; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\"\n"
	   + "                    align=\"right\">\n" + "                  Subtotal\n" + "                </th>\n"
	   + "              </tr>\n" + "              <tr>\n"
	   + "                <td height=\"1\" style=\"background: #bebebe;\" colspan=\"4\"></td>\n"
	   + "              </tr>\n" + "              <tr>\n" + "                <td height=\"10\" colspan=\"4\"></td>\n"
	   + "              </tr>\n";

	public static final String lastPart =
	   "\n" + "              </tbody>\n" + "            </table>\n" + "          </td>\n" + "        </tr>\n"
		  + "        <tr>\n" + "          <td height=\"20\"></td>\n" + "        </tr>\n" + "        </tbody>\n"
		  + "      </table>\n" + "    </td>\n" + "  </tr>\n" + "  </tbody>\n" + "</table>\n"
		  + "<!-- /Order Details -->\n" + "\n" + "\n" + "<!-- Total -->\n"
		  + "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\n"
		  + "  <tbody>\n" + "  <tr>\n" + "    <td>\n"
		  + "      <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\">\n"
		  + "        <tbody>\n" + "        <tr>\n" + "          <td>\n" + "\n" + "            <!-- Table Total -->\n"
		  + "            <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\n"
		  + "              <tbody>\n" + "              <tr>\n"
		  + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\n"
		  + "                  Subtotal\n" + "                </td>\n"
		  + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; white-space:nowrap;\"\n"
		  + "                    width=\"80\">\n" + "                  ${{subtotal}}\n" + "                </td>\n"
		  + "              </tr>\n" + "              <tr>\n"
		  + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\n"
		  + "                  Shipping\n" + "                </td>\n"
		  + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\n"
		  + "                  ${{shipping}}\n" + "                </td>\n" + "              </tr>\n"
		  + "              <tr>\n"
		  + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #000; line-height: 22px; vertical-align: top; text-align:right; \">\n"
		  + "                  <strong>Grand Total</strong>\n" + "                </td>\n"
		  + "                <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #000; line-height: 22px; vertical-align: top; text-align:right; \">\n"
		  + "                  <strong>${{total-price}}</strong>\n" + "                </td>\n"
		  + "              </tr>\n" + "\n" + "              </tbody>\n" + "            </table>\n"
		  + "            <!-- /Table Total -->\n" + "\n" + "          </td>\n" + "        </tr>\n"
		  + "        </tbody>\n" + "      </table>\n" + "    </td>\n" + "  </tr>\n" + "  </tbody>\n" + "</table>\n"
		  + "<!-- /Total -->\n" + "\n" + "<!-- Information -->\n"
		  + "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\n"
		  + "  <tbody>\n" + "  <tr>\n" + "    <td>\n"
		  + "      <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\">\n"
		  + "        <tbody>\n" + "        <tr>\n" + "        <tr class=\"hiddenMobile\">\n"
		  + "          <td height=\"60\"></td>\n" + "        </tr>\n" + "        <tr class=\"visibleMobile\">\n"
		  + "          <td height=\"40\"></td>\n" + "        </tr>\n" + "\n" + "        <tr>\n" + "          <td>\n"
		  + "            <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\n"
		  + "              <tbody>\n" + "              <tr>\n" + "                <td>\n"
		  + "                  <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"left\" class=\"col\">\n"
		  + "                    <tbody>\n" + "                    <tr class=\"hiddenMobile\">\n"
		  + "                      <td height=\"35\"></td>\n" + "                    </tr>\n"
		  + "                    <tr class=\"visibleMobile\">\n" + "                      <td height=\"20\"></td>\n"
		  + "                    </tr>\n" + "                    <tr>\n"
		  + "                      <td style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\n"
		  + "                        <strong>INFORMATION</strong>\n" + "                      </td>\n"
		  + "                    </tr>\n" + "                    <tr>\n"
		  + "                      <td width=\"100%\" height=\"10\"></td>\n" + "                    </tr>\n"
		  + "                    <tr>\n"
		  + "                      <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\n"
		  + "                        {{name}}<br>{{street1}}<br> {{street2}} {{city}}<br> {{zip-code}}, {{country}}<br> {{email}}\n"
		  + "                      </td>\n" + "                    </tr>\n" + "                    </tbody>\n"
		  + "                  </table>\n" + "\n" + "\n"
		  + "                  <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"right\" class=\"col\">\n"
		  + "                    <tbody>\n" + "                    <tr class=\"hiddenMobile\">\n"
		  + "                      <td height=\"35\"></td>\n" + "                    </tr>\n"
		  + "                    <tr class=\"visibleMobile\">\n" + "                      <td height=\"20\"></td>\n"
		  + "                    </tr>\n" + "                    <tr>\n"
		  + "                      <td style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\n"
		  + "                        <strong>SHIPPING METHOD</strong>\n" + "                      </td>\n"
		  + "                    </tr>\n" + "                    <tr>\n"
		  + "                      <td width=\"100%\" height=\"10\"></td>\n" + "                    </tr>\n"
		  + "                    <tr>\n"
		  + "                      <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\n"
		  + "                        {{shipping-method}}\n" + "                      </td>\n"
		  + "                    </tr>\n" + "                    </tbody>\n" + "                  </table>\n"
		  + "                </td>\n" + "              </tr>\n" + "              </tbody>\n" + "            </table>\n"
		  + "          </td>\n" + "        </tr>\n" + "        <tr class=\"hiddenMobile\">\n"
		  + "          <td height=\"60\"></td>\n" + "        </tr>\n" + "        <tr class=\"visibleMobile\">\n"
		  + "          <td height=\"30\"></td>\n" + "        </tr>\n" + "        </tbody>\n" + "      </table>\n"
		  + "    </td>\n" + "  </tr>\n" + "  </tbody>\n" + "</table>\n" + "<!-- /Information -->\n" + "\n" + "\n"
		  + "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\n"
		  + "\n" + "  <tr>\n" + "    <td>\n"
		  + "      <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\"\n"
		  + "             style=\"border-radius: 0 0 10px 10px;\">\n" + "        <tr>\n" + "          <td>\n"
		  + "            <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\n"
		  + "              <tbody>\n" + "              <tr>\n"
		  + "                <td style=\"font-size: 12px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: left;\">\n"
		  + "                  Have a nice day.\n" + "                </td>\n" + "              </tr>\n"
		  + "              </tbody>\n" + "            </table>\n" + "          </td>\n" + "        </tr>\n"
		  + "        <tr class=\"spacer\">\n" + "          <td height=\"50\"></td>\n" + "        </tr>\n" + "\n"
		  + "      </table>\n" + "    </td>\n" + "  </tr>\n" + "  <tr>\n" + "    <td height=\"20\"></td>\n"
		  + "  </tr>\n" + "</table>\n";
}
